### ISSUE TITLE
Document Redis use case

### ISSUE THREAD

**Issue by almereyda** [mmz-srf/passbolt-helm#16]
As a user of the Passbolt Charge, I need to enable a deployment with secure and valid Redis configuration, in order to use its features, presumably rolling updates without invalidating current user sessions.

**Comment by claudio-walser** [comment]
Hi Jon

Sorry for answering so late.
As stated in the README and values file (https://github.com/mmz-srf/passbolt-helm/blob/master/values.yaml#L41), you would need to provide a redis installation by your own and just pass the url to this helm charts. I would probably give the RedisEnterprise operator a try: https://operatorhub.io/operator/redis-enterprise

Hope this helps, regards
Claudio

**Comment by almereyda** [comment]
Thank you for the answer. These resources were known to me, but oftentimes it is more easy to check an example, if one understood them well.

I might as well try this myself again and publish the result somewhere on the internet, for interested strangers to follow along.

Thank you for your support.

**Comment by claudio-walser** [comment]
Hi Jon

Yes you are right.
FYI: @AnatomicJC ist working on integrating redis, similar as it is done with mysql.
The issue he opened is here: https://github.com/mmz-srf/passbolt-helm/issues/19
So if you stay patient just a little more, your need might probably be fulfilled as well ;-)

Thank you and best regards
Claudio

**Comment by almereyda** [comment]
I am. Many thanks for caring!
