### ISSUE TITLE
Rotating GPG keys breaks deployment

### ISSUE THREAD

**Issue by XL-Lewis** [mmz-srf/passbolt-helm#25]
Regenerating the GPG and JWT keys on your install doesn't work properly as the secrets are only repopulated on a fresh install. This took me a hilarious amount of time to figure out (:

May be worth including a note that updating keys requires an update to the relevant secrets, or removing the pre-install hook from the secret creation.

Cheers!

**Comment by claudio-walser** [comment]
Hi Lewis

Sorry for the inconvenience this have caused.
Chart Version 1.8.2 will provide the fix you mentioned.

Please close the issue if this fits your needs.
