### ISSUE TITLE
Add EMAIL_DEFAULT_FROM_NAME env variable to documentation

### ISSUE THREAD

**Issue by pabloelcolombiano** [mmz-srf/passbolt-helm#26]
Following the issue reported [by the community here](https://community.passbolt.com/t/error-the-sender-name-should-not-be-empty-when-accessing-email-server-settings/6417/2), the documentation ought to be updated.

**Comment by claudio-walser** [comment]
Hi @pabloelcolombiano
I've added this information in the docs accordingly.

Thank you for opening the ticket.
